<a href="https://colab.research.google.com/github/amukund8/Projects/blob/main/torchtesting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

# Create a 2D tensor representing raw scores for three classes (3 classes, 4 samples)
raw_scores = torch.tensor([[1.0, 2.0, 3.0],
                           [4.0, 5.0, 6.0],
                           [7.0, 8.0, 9.0],
                           [10.0, 11.0, 12.0]])

# Apply softmax along dimension 1 (classes)
softmax = nn.Softmax(dim=1)
output_probs = softmax(raw_scores)

print("Raw scores:")
print(raw_scores)
print("\nSoftmax probabilities:")
print(output_probs)


Raw scores:
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

Softmax probabilities:
tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])


In [ ]:
import torch
import torch.nn as nn

# Create a 2D tensor representing raw scores for three classes (3 classes, 4 samples)
raw_scores = torch.tensor([[1.0, 2.0, 3.0],
                           [4.0, 5.0, 6.0],
                           [7.0, 8.0, 9.0],
                           [10.0, 11.0, 12.0]])

# Apply softmax along dimension 1 (classes)
softmax = nn.Softmax(dim=0)
output_probs = softmax(raw_scores)

print("Raw scores:")
print(raw_scores)
print("\nSoftmax probabilities:")
print(output_probs)


Raw scores:
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

Softmax probabilities:
tensor([[1.1727e-04, 1.1727e-04, 1.1727e-04],
        [2.3554e-03, 2.3554e-03, 2.3554e-03],
        [4.7309e-02, 4.7309e-02, 4.7309e-02],
        [9.5022e-01, 9.5022e-01, 9.5022e-01]])


In [ ]:
o1= torch.tensor([[-0.0186,  0.0053, -0.0376,  0.0025],
        [-0.0214,  0.0066, -0.0329,  0.0026],
        [-0.0175,  0.0053, -0.0377,  0.0032],
        [-0.0204,  0.0084, -0.0360,  0.0002],
        [-0.0215,  0.0035, -0.0383,  0.0053],
        [-0.0213,  0.0021, -0.0499,  0.0030],
        [-0.0187,  0.0051, -0.0460, -0.0052],
        [-0.0187,  0.0095, -0.0404, -0.0110],
        [-0.0183,  0.0097, -0.0409, -0.0200],
        [-0.0194,  0.0088, -0.0403, -0.0074],
        [-0.0220,  0.0068, -0.0326,  0.0034]])

In [ ]:
len(o1)

11

In [ ]:
target=torch.tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
target[1]

tensor(3)

In [ ]:
len(target)

11

In [ ]:
sm=nn.Softmax()
preds=sm(o1)

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1518: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


In [ ]:
print(preds)

tensor([[0.2483, 0.2543, 0.2437, 0.2536],
        [0.2474, 0.2545, 0.2446, 0.2535],
        [0.2485, 0.2542, 0.2435, 0.2537],
        [0.2479, 0.2551, 0.2440, 0.2530],
        [0.2478, 0.2541, 0.2437, 0.2545],
        [0.2488, 0.2546, 0.2417, 0.2549],
        [0.2493, 0.2553, 0.2426, 0.2527],
        [0.2491, 0.2562, 0.2437, 0.2510],
        [0.2497, 0.2568, 0.2441, 0.2493],
        [0.2488, 0.2559, 0.2436, 0.2518],
        [0.2473, 0.2545, 0.2446, 0.2536]])


In [ ]:
ex=torch.tensor(0.2545)
ex2=torch.tensor(0.24523)
a=[ex, ex2]
a

[tensor(0.2545), tensor(0.2452)]

In [ ]:
target.size(0)

11

In [ ]:
target.size(0)

11

In [ ]:
correct += (predicted == target).sum().item()

In [ ]:
correct

2

In [ ]:
correct=0
total=0
index=0
max_vals=[]
pred_vals=[]
for imageprob in preds:

  #print(imageprob)
  predicted = torch.max(imageprob)
  max_vals.append(predicted)
  #print(predicted)
  indices = torch.where(imageprob == predicted)
  predicted = indices[0][0]
  pred_vals.append(predicted)
  #print(predicted)
  total +=target.size(0)
  if predicted==target[index]:
    correct+=1
  #correct += (predicted == label).sum().item()

  index+=1




tensor([0.2483, 0.2543, 0.2437, 0.2536])
tensor(0.2543)
tensor(1)
tensor([0.2474, 0.2545, 0.2446, 0.2535])
tensor(0.2545)
tensor(1)
tensor([0.2485, 0.2542, 0.2435, 0.2537])
tensor(0.2542)
tensor(1)
tensor([0.2479, 0.2551, 0.2440, 0.2530])
tensor(0.2551)
tensor(1)
tensor([0.2478, 0.2541, 0.2437, 0.2545])
tensor(0.2545)
tensor(3)
tensor([0.2488, 0.2546, 0.2417, 0.2549])
tensor(0.2549)
tensor(3)
tensor([0.2493, 0.2553, 0.2426, 0.2527])
tensor(0.2553)
tensor(1)
tensor([0.2491, 0.2562, 0.2437, 0.2510])
tensor(0.2562)
tensor(1)
tensor([0.2497, 0.2568, 0.2441, 0.2493])
tensor(0.2568)
tensor(1)
tensor([0.2488, 0.2559, 0.2436, 0.2518])
tensor(0.2559)
tensor(1)
tensor([0.2473, 0.2545, 0.2446, 0.2536])
tensor(0.2545)
tensor(1)


In [ ]:
correct

2

In [ ]:
correct

2

In [ ]:
predicted

tensor(1)

In [ ]:
predicted = torch.max(preds)

In [ ]:
predicted

tensor(0.2568)

In [ ]:
index = torch.where(preds == predicted)

In [ ]:
index

In [ ]:
import torch

# Create a tensor
my_tensor = torch.tensor([1, 3, 7, 5, 9, 11, 13])

# Specify the value you want to find
value_to_find = 5

# Use torch.where to find the indices where the tensor is equal to the specified value
indices = torch.where(my_tensor == value_to_find)

print("Original tensor:", my_tensor)
print(f"Indices of {value_to_find}:", indices)

indices_as_tensor = indices[0][0]
print("Indices as tensor:", indices_as_tensor)
