<a href="https://colab.research.google.com/github/amukund8/Projects/blob/main/torchnormalize.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader

# Define a custom dataset class with random data
class RandomDataset(Dataset):
    def __init__(self, num_samples, input_size, target_size):
        self.num_samples = num_samples
        self.input_size = input_size
        self.target_size = target_size

    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        # Generate random input data and target labels for each sample
        input_data = torch.randn(self.input_size)
        target_label = torch.randint(0, 2, (self.target_size,)).item()

        sample = {'input': input_data, 'target': target_label}
        return sample

# Create an instance of the RandomDataset
num_samples = 1000
input_size = 64
target_size = 1
random_dataset = RandomDataset(num_samples, input_size, target_size)

# Create a DataLoader for the dataset
batch_size = 64
shuffle = True
num_workers = 4

random_data_loader = DataLoader(random_dataset, batch_size=batch_size, shuffle=shuffle, num_workers=num_workers)

# Iterate through the DataLoader
for batch in random_data_loader:
    inputs = batch['input']  # Access the input data
    targets = batch['target']  # Access the target labels

    # Your training or evaluation logic here
    # Forward pass, backward pass, optimization, etc.



/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(


In [ ]:
import torch
import numpy as np
from torch.utils.data import Dataset, DataLoader

# Define a custom dataset class with random data
class RandomDataset(Dataset):
    def __init__(self, num_samples, input_size, target_size):
        self.num_samples = num_samples
        self.input_size = input_size
        self.target_size = target_size

    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        # Generate random input data and target labels for each sample
        input_data = torch.randn(self.input_size)
        data=input_data
        data=data.numpy()

        # Normalization
        data=(data-np.min(data))/(np.max(data)-np.min(data))
        data=torch.from_numpy(data)

        target_label = torch.randint(0, 2, (self.target_size,)).item()

        sample = {'input': data, 'target': target_label}
        return sample

# Create an instance of the RandomDataset
num_samples = 1000
input_size = 64
target_size = 1
random_dataset = RandomDataset(num_samples, input_size, target_size)


In [ ]:
len(random_dataset[0])

2

In [ ]:
random_dataset[0]

{'input': tensor([0.5749, 0.5289, 0.4452, 0.5880, 0.3583, 0.5628, 0.2764, 0.7407, 0.8287,
         0.8142, 0.5351, 0.1742, 0.6941, 0.6983, 0.9807, 0.7448, 0.5505, 0.3414,
         0.4764, 0.3129, 0.1642, 0.2669, 0.4053, 0.6850, 0.1844, 0.0884, 0.5522,
         0.7542, 0.3978, 0.6823, 0.6835, 0.1774, 0.3153, 0.7405, 0.4472, 0.2580,
         0.6041, 0.6314, 0.8288, 0.4873, 1.0000, 0.4058, 0.3129, 0.5651, 0.7645,
         0.8182, 0.6271, 0.5824, 0.2928, 0.4116, 0.3896, 0.5581, 0.6228, 0.4898,
         0.0000, 0.8174, 0.7672, 0.1213, 0.8637, 0.5931, 0.4104, 0.7569, 0.9047,
         0.5281]),
 'target': 1}

In [ ]:
len(random_dataset[0]['input'])

64

In [ ]:
d=random_dataset[2]

In [ ]:
print(d)

{'input': tensor([0.3616, 0.3863, 0.4221, 0.3085, 0.4379, 0.5485, 0.6355, 0.3933, 0.5852,
        0.4410, 0.4668, 0.7075, 0.5854, 0.5143, 0.3424, 0.6132, 0.2613, 0.5351,
        0.6887, 0.0000, 0.1977, 0.4886, 0.2077, 0.8075, 0.2454, 0.2989, 0.4364,
        0.6807, 0.2567, 0.5061, 0.6282, 0.0647, 0.1654, 0.5373, 0.5191, 0.4462,
        0.4626, 0.3587, 0.4351, 0.4041, 0.2836, 0.5315, 0.4987, 0.3333, 0.4632,
        0.4831, 0.2591, 0.8141, 0.4359, 0.5570, 0.3095, 0.3526, 0.4568, 0.5106,
        0.4722, 1.0000, 0.6573, 0.6309, 0.3160, 0.3360, 0.3831, 0.3876, 0.3084,
        0.4619]), 'target': 0}


In [ ]:
print(d['input'])

tensor([0.3616, 0.3863, 0.4221, 0.3085, 0.4379, 0.5485, 0.6355, 0.3933, 0.5852,
        0.4410, 0.4668, 0.7075, 0.5854, 0.5143, 0.3424, 0.6132, 0.2613, 0.5351,
        0.6887, 0.0000, 0.1977, 0.4886, 0.2077, 0.8075, 0.2454, 0.2989, 0.4364,
        0.6807, 0.2567, 0.5061, 0.6282, 0.0647, 0.1654, 0.5373, 0.5191, 0.4462,
        0.4626, 0.3587, 0.4351, 0.4041, 0.2836, 0.5315, 0.4987, 0.3333, 0.4632,
        0.4831, 0.2591, 0.8141, 0.4359, 0.5570, 0.3095, 0.3526, 0.4568, 0.5106,
        0.4722, 1.0000, 0.6573, 0.6309, 0.3160, 0.3360, 0.3831, 0.3876, 0.3084,
        0.4619])


In [ ]:
a=torch.max(d['input'])

In [ ]:
print(a.item())

1.0


In [ ]:
import torch
import numpy as np
from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms


# Define a custom dataset class with random data
class RandomDataset(Dataset):
    def __init__(self, num_samples, input_size, target_size,input,label):
        self.num_samples = num_samples
        self.input_size = input_size
        self.target_size = target_size
        self.target_label=label
        self.input=input

    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        # Generate random input data and target labels for each sample
        input_data = self.input
        data=input_data

        # Normalizaiton

        target_label=self.target_label


        #sample = {'input': data, 'target': target_label}
        return data,target_label

# Create an instance of the RandomDataset
torch.manual_seed(42)
input_size = (3,5,5)
target_size = 1
input= torch.randn(input_size)

target_label = torch.randint(0, 3, (target_size,)).item()
num_samples = 50

random_dataset = RandomDataset(num_samples, input_size, target_size,input,target_label)
a=random_dataset



In [ ]:
a.__getitem__(1)

(tensor([[[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784],
          [-1.2345, -0.0431, -1.6047, -0.7521,  1.6487],
          [-0.3925, -1.4036, -0.7279, -0.5594, -0.7688],
          [ 0.7624,  1.6423, -0.1596, -0.4974,  0.4396],
          [-0.7581,  1.0783,  0.8008,  1.6806,  1.2791]],
 
         [[ 1.2964,  0.6105,  1.3347, -0.2316,  0.0418],
          [-0.2516,  0.8599, -1.3847, -0.8712, -0.2234],
          [ 1.7174,  0.3189, -0.4245,  0.3057, -0.7746],
          [-1.5576,  0.9956, -0.8798, -0.6011, -1.2742],
          [ 2.1228, -1.2347, -0.4879, -0.9138, -0.6581]],
 
         [[ 0.0780,  0.5258, -0.4880,  1.1914, -0.8140],
          [-0.7360, -1.4032,  0.0360, -0.0635, -0.1423],
          [ 0.1971, -1.1441,  0.3383,  1.6992,  0.0109],
          [-0.3387, -1.3407,  0.4584, -0.5644,  1.0563],
          [-1.4692,  1.4332,  0.7440, -0.4816, -1.0495]]]),
 2)

In [ ]:
a.__getitem__(1)

(tensor([[[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784],
          [-1.2345, -0.0431, -1.6047, -0.7521,  1.6487],
          [-0.3925, -1.4036, -0.7279, -0.5594, -0.7688],
          [ 0.7624,  1.6423, -0.1596, -0.4974,  0.4396],
          [-0.7581,  1.0783,  0.8008,  1.6806,  1.2791]],
 
         [[ 1.2964,  0.6105,  1.3347, -0.2316,  0.0418],
          [-0.2516,  0.8599, -1.3847, -0.8712, -0.2234],
          [ 1.7174,  0.3189, -0.4245,  0.3057, -0.7746],
          [-1.5576,  0.9956, -0.8798, -0.6011, -1.2742],
          [ 2.1228, -1.2347, -0.4879, -0.9138, -0.6581]],
 
         [[ 0.0780,  0.5258, -0.4880,  1.1914, -0.8140],
          [-0.7360, -1.4032,  0.0360, -0.0635, -0.1423],
          [ 0.1971, -1.1441,  0.3383,  1.6992,  0.0109],
          [-0.3387, -1.3407,  0.4584, -0.5644,  1.0563],
          [-1.4692,  1.4332,  0.7440, -0.4816, -1.0495]]]),
 2)

In [ ]:
a.__getitem__(1)[0]

tensor([[[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784],
         [-1.2345, -0.0431, -1.6047, -0.7521,  1.6487],
         [-0.3925, -1.4036, -0.7279, -0.5594, -0.7688],
         [ 0.7624,  1.6423, -0.1596, -0.4974,  0.4396],
         [-0.7581,  1.0783,  0.8008,  1.6806,  1.2791]],

        [[ 1.2964,  0.6105,  1.3347, -0.2316,  0.0418],
         [-0.2516,  0.8599, -1.3847, -0.8712, -0.2234],
         [ 1.7174,  0.3189, -0.4245,  0.3057, -0.7746],
         [-1.5576,  0.9956, -0.8798, -0.6011, -1.2742],
         [ 2.1228, -1.2347, -0.4879, -0.9138, -0.6581]],

        [[ 0.0780,  0.5258, -0.4880,  1.1914, -0.8140],
         [-0.7360, -1.4032,  0.0360, -0.0635, -0.1423],
         [ 0.1971, -1.1441,  0.3383,  1.6992,  0.0109],
         [-0.3387, -1.3407,  0.4584, -0.5644,  1.0563],
         [-1.4692,  1.4332,  0.7440, -0.4816, -1.0495]]])

In [ ]:
tensor_list=[]
for i in range(len(a)):
  tensor_list.append(a.__getitem__(i)[0])




In [ ]:
len(tensor_list)

50

In [ ]:
tensor_list=torch.stack(tensor_list,dim=0)

In [ ]:
tensor_list.shape

torch.Size([50, 3, 5, 5])

In [ ]:
mean = torch.mean(tensor_list, dim=(0, 2, 3), keepdim=True)
std = torch.std(tensor_list, dim=(0, 2, 3), keepdim=True)


In [ ]:
print(mean)
print(std)

tensor([[[[ 0.1327]],

         [[-0.0866]],

         [[-0.0907]]]])
tensor([[[[1.1444]],

         [[0.9978]],

         [[0.8707]]]])


In [ ]:
tensor_list.shape

torch.Size([50, 3, 5, 5])

In [ ]:
tensor_list


tensor([[[[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784],
          [-1.2345, -0.0431, -1.6047, -0.7521,  1.6487],
          [-0.3925, -1.4036, -0.7279, -0.5594, -0.7688],
          [ 0.7624,  1.6423, -0.1596, -0.4974,  0.4396],
          [-0.7581,  1.0783,  0.8008,  1.6806,  1.2791]],

         [[ 1.2964,  0.6105,  1.3347, -0.2316,  0.0418],
          [-0.2516,  0.8599, -1.3847, -0.8712, -0.2234],
          [ 1.7174,  0.3189, -0.4245,  0.3057, -0.7746],
          [-1.5576,  0.9956, -0.8798, -0.6011, -1.2742],
          [ 2.1228, -1.2347, -0.4879, -0.9138, -0.6581]],

         [[ 0.0780,  0.5258, -0.4880,  1.1914, -0.8140],
          [-0.7360, -1.4032,  0.0360, -0.0635, -0.1423],
          [ 0.1971, -1.1441,  0.3383,  1.6992,  0.0109],
          [-0.3387, -1.3407,  0.4584, -0.5644,  1.0563],
          [-1.4692,  1.4332,  0.7440, -0.4816, -1.0495]]],


        [[[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784],
          [-1.2345, -0.0431, -1.6047, -0.7521,  1.6487],
          [-0.3925, -1.

In [ ]:

'''

# Define a custom dataset class with random data
class Normalize(Dataset):
    def __init__(self,input,label,transform):

        self.target_label=label
        self.input=input
        self.transform=transform

    def __len__(self):
        return len(self.target_label)

    def __getitem__(self, idx):
        # Generate random input data and target labels for each sample
        input_data = self.input
        data=input_data

        # Normalizaiton

        target_label=self.target_label

        if self.transform:
            sample = self.transform(sample)

        #sample = {'input': data, 'target': target_label}
        return data,target_label




transformed = Normalize(tensor_list,target_label)
'''



"\n\n# Define a custom dataset class with random data\nclass Normalize(Dataset):\n    def __init__(self,input,label,transform):\n\n        self.target_label=label\n        self.input=input\n        self.transform=transform\n\n    def __len__(self):\n        return len(self.target_label)\n\n    def __getitem__(self, idx):\n        # Generate random input data and target labels for each sample\n        input_data = self.input\n        data=input_data\n        \n        # Normalizaiton\n        \n        target_label=self.target_label\n\n        if self.transform:\n            sample = self.transform(sample)\n\n        #sample = {'input': data, 'target': target_label}\n        return data,target_label\n\n\n\n\ntransformed = Normalize(tensor_list,target_label)\n"

In [ ]:
normalize = transforms.Compose([
    transforms.Normalize(mean=mean, std=std)
])

hello=normalize(tensor_list)

In [ ]:
tensor_list[0]

tensor([[[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784],
         [-1.2345, -0.0431, -1.6047, -0.7521,  1.6487],
         [-0.3925, -1.4036, -0.7279, -0.5594, -0.7688],
         [ 0.7624,  1.6423, -0.1596, -0.4974,  0.4396],
         [-0.7581,  1.0783,  0.8008,  1.6806,  1.2791]],

        [[ 1.2964,  0.6105,  1.3347, -0.2316,  0.0418],
         [-0.2516,  0.8599, -1.3847, -0.8712, -0.2234],
         [ 1.7174,  0.3189, -0.4245,  0.3057, -0.7746],
         [-1.5576,  0.9956, -0.8798, -0.6011, -1.2742],
         [ 2.1228, -1.2347, -0.4879, -0.9138, -0.6581]],

        [[ 0.0780,  0.5258, -0.4880,  1.1914, -0.8140],
         [-0.7360, -1.4032,  0.0360, -0.0635, -0.1423],
         [ 0.1971, -1.1441,  0.3383,  1.6992,  0.0109],
         [-0.3387, -1.3407,  0.4584, -0.5644,  1.0563],
         [-1.4692,  1.4332,  0.7440, -0.4816, -1.0495]]])

In [ ]:
transfromed[0]

tensor([[[ 1.5678,  1.1836,  0.6711, -1.9558,  0.4768],
         [-1.1947, -0.1536, -1.5181, -0.7732,  1.3247],
         [-0.4589, -1.3424, -0.7520, -0.6048, -0.7878],
         [ 0.5503,  1.3191, -0.2554, -0.5506,  0.2681],
         [-0.7784,  0.8263,  0.5838,  1.3526,  1.0017]],

        [[ 1.3861,  0.6986,  1.4245, -0.1453,  0.1287],
         [-0.1653,  0.9486, -1.3010, -0.7864, -0.1371],
         [ 1.8080,  0.4064, -0.3387,  0.3932, -0.6895],
         [-1.4742,  1.0846, -0.7949, -0.5157, -1.1902],
         [ 2.2143, -1.1506, -0.4022, -0.8291, -0.5728]],

        [[ 0.1937,  0.7080, -0.4563,  1.4724, -0.8307],
         [-0.7411, -1.5075,  0.1455,  0.0312, -0.0593],
         [ 0.3305, -1.2099,  0.4927,  2.0556,  0.1166],
         [-0.2849, -1.4356,  0.6306, -0.5441,  1.3173],
         [-1.5831,  1.7501,  0.9585, -0.4490, -1.1011]]])

In [ ]:
label_list=[]
for i in range(len(a)):
  label=np.int64(a.__getitem__(i)[1])
  print(type(label))
  label_list.append(label)

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'nu

In [ ]:
label_list

[2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

In [ ]:
tensor_list.shape

torch.Size([50, 3, 5, 5])

In [ ]:
tensor_list[0].shape

torch.Size([3, 5, 5])

In [ ]:
tensor_list[0]

tensor([[[ 1.9269,  1.4873,  0.9007, -2.1055,  0.6784],
         [-1.2345, -0.0431, -1.6047, -0.7521,  1.6487],
         [-0.3925, -1.4036, -0.7279, -0.5594, -0.7688],
         [ 0.7624,  1.6423, -0.1596, -0.4974,  0.4396],
         [-0.7581,  1.0783,  0.8008,  1.6806,  1.2791]],

        [[ 1.2964,  0.6105,  1.3347, -0.2316,  0.0418],
         [-0.2516,  0.8599, -1.3847, -0.8712, -0.2234],
         [ 1.7174,  0.3189, -0.4245,  0.3057, -0.7746],
         [-1.5576,  0.9956, -0.8798, -0.6011, -1.2742],
         [ 2.1228, -1.2347, -0.4879, -0.9138, -0.6581]],

        [[ 0.0780,  0.5258, -0.4880,  1.1914, -0.8140],
         [-0.7360, -1.4032,  0.0360, -0.0635, -0.1423],
         [ 0.1971, -1.1441,  0.3383,  1.6992,  0.0109],
         [-0.3387, -1.3407,  0.4584, -0.5644,  1.0563],
         [-1.4692,  1.4332,  0.7440, -0.4816, -1.0495]]])

In [ ]:
type(label_list[0])

numpy.int64

In [ ]:
normalize = transforms.Compose([
    transforms.Normalize(mean=mean, std=std)
])



# Define a custom dataset class with random data
class Normalized(Dataset):
    def __init__(self,input,label,transform):

        self.label=label
        self.input=input
        self.transform=transform

    def __len__(self):
        return len(self.target_label)

    def __getitem__(self, idx):
        # Generate random input data and target labels for each sample
        input_data = self.input[idx]
        data=input_data

        # Normalizaiton

        target_label=self.label[idx]
        print(data.shape)

        if self.transform:
           norm = self.transform(self.input)
           data=norm[idx]


        #sample = {'input': data, 'target': target_label}
        return data,target_label




transformed1 = Normalized(tensor_list,label_list,transform=normalize)




In [ ]:
transformed

In [ ]:
transformed1.__getitem__(1)

torch.Size([3, 5, 5])


(tensor([[[ 1.5678,  1.1836,  0.6711, -1.9558,  0.4768],
          [-1.1947, -0.1536, -1.5181, -0.7732,  1.3247],
          [-0.4589, -1.3424, -0.7520, -0.6048, -0.7878],
          [ 0.5503,  1.3191, -0.2554, -0.5506,  0.2681],
          [-0.7784,  0.8263,  0.5838,  1.3526,  1.0017]],
 
         [[ 1.3861,  0.6986,  1.4245, -0.1453,  0.1287],
          [-0.1653,  0.9486, -1.3010, -0.7864, -0.1371],
          [ 1.8080,  0.4064, -0.3387,  0.3932, -0.6895],
          [-1.4742,  1.0846, -0.7949, -0.5157, -1.1902],
          [ 2.2143, -1.1506, -0.4022, -0.8291, -0.5728]],
 
         [[ 0.1937,  0.7080, -0.4563,  1.4724, -0.8307],
          [-0.7411, -1.5075,  0.1455,  0.0312, -0.0593],
          [ 0.3305, -1.2099,  0.4927,  2.0556,  0.1166],
          [-0.2849, -1.4356,  0.6306, -0.5441,  1.3173],
          [-1.5831,  1.7501,  0.9585, -0.4490, -1.1011]]]),
 2)

In [ ]:
transformed1[0]

torch.Size([3, 5, 5])


(tensor([[[ 1.5678,  1.1836,  0.6711, -1.9558,  0.4768],
          [-1.1947, -0.1536, -1.5181, -0.7732,  1.3247],
          [-0.4589, -1.3424, -0.7520, -0.6048, -0.7878],
          [ 0.5503,  1.3191, -0.2554, -0.5506,  0.2681],
          [-0.7784,  0.8263,  0.5838,  1.3526,  1.0017]],
 
         [[ 1.3861,  0.6986,  1.4245, -0.1453,  0.1287],
          [-0.1653,  0.9486, -1.3010, -0.7864, -0.1371],
          [ 1.8080,  0.4064, -0.3387,  0.3932, -0.6895],
          [-1.4742,  1.0846, -0.7949, -0.5157, -1.1902],
          [ 2.2143, -1.1506, -0.4022, -0.8291, -0.5728]],
 
         [[ 0.1937,  0.7080, -0.4563,  1.4724, -0.8307],
          [-0.7411, -1.5075,  0.1455,  0.0312, -0.0593],
          [ 0.3305, -1.2099,  0.4927,  2.0556,  0.1166],
          [-0.2849, -1.4356,  0.6306, -0.5441,  1.3173],
          [-1.5831,  1.7501,  0.9585, -0.4490, -1.1011]]]),
 2)

In [ ]:
hello[1]

tensor([[[ 1.5678,  1.1836,  0.6711, -1.9558,  0.4768],
         [-1.1947, -0.1536, -1.5181, -0.7732,  1.3247],
         [-0.4589, -1.3424, -0.7520, -0.6048, -0.7878],
         [ 0.5503,  1.3191, -0.2554, -0.5506,  0.2681],
         [-0.7784,  0.8263,  0.5838,  1.3526,  1.0017]],

        [[ 1.3861,  0.6986,  1.4245, -0.1453,  0.1287],
         [-0.1653,  0.9486, -1.3010, -0.7864, -0.1371],
         [ 1.8080,  0.4064, -0.3387,  0.3932, -0.6895],
         [-1.4742,  1.0846, -0.7949, -0.5157, -1.1902],
         [ 2.2143, -1.1506, -0.4022, -0.8291, -0.5728]],

        [[ 0.1937,  0.7080, -0.4563,  1.4724, -0.8307],
         [-0.7411, -1.5075,  0.1455,  0.0312, -0.0593],
         [ 0.3305, -1.2099,  0.4927,  2.0556,  0.1166],
         [-0.2849, -1.4356,  0.6306, -0.5441,  1.3173],
         [-1.5831,  1.7501,  0.9585, -0.4490, -1.1011]]])